import sqlite3
import os
from datetime import datetime

def get_weekly_stats():
    """Get violation stats from database"""
    conn = sqlite3.connect("database/viosense.db")
    cursor = conn.cursor()

    # Total violations
    cursor.execute("SELECT COUNT(*) FROM violations")
    total = cursor.fetchone()[0]

    # Most common violation
    cursor.execute("""
        SELECT violation_type, COUNT(*) as cnt
        FROM violations
        GROUP BY violation_type
        ORDER BY cnt DESC LIMIT 1
    """)
    top_violation = cursor.fetchone()

    # Most dangerous location
    cursor.execute("""
        SELECT location, COUNT(*) as cnt
        FROM violations
        GROUP BY location
        ORDER BY cnt DESC LIMIT 1
    """)
    top_location = cursor.fetchone()

    # Critical violations
    cursor.execute("""
        SELECT COUNT(*) FROM violations
        WHERE risk_level = 'CRITICAL'
    """)
    critical = cursor.fetchone()[0]

    # Repeat offenders
    cursor.execute("""
        SELECT COUNT(*) FROM vehicles
        WHERE total_violations >= 3
    """)
    repeat = cursor.fetchone()[0]

    conn.close()

    return {
        'total': total,
        'top_violation': top_violation[0] if top_violation else 'N/A',
        'top_violation_count': top_violation[1] if top_violation else 0,
        'top_location': top_location[0] if top_location else 'N/A',
        'top_location_count': top_location[1] if top_location else 0,
        'critical': critical,
        'repeat_offenders': repeat
    }

def generate_ai_summary():
    """
    Generate AI-powered weekly summary using Claude API
    """
    stats = get_weekly_stats()

    # Try Claude API
    try:
        import anthropic

        client = anthropic.Anthropic(
            api_key=os.environ.get("ANTHROPIC_API_KEY", "")
        )

        prompt = f"""
You are VioSense AI, a traffic enforcement intelligence system for Bengaluru.

Generate a concise weekly traffic violation summary report based on this data:
- Total violations detected: {stats['total']}
- Most common violation: {stats['top_violation']} ({stats['top_violation_count']} cases)
- Highest risk location: {stats['top_location']} ({stats['top_location_count']} violations)
- Critical risk violations: {stats['critical']}
- Repeat offenders identified: {stats['repeat_offenders']}

Write a professional 5-6 line traffic safety report with:
1. Key findings summary
2. Most concerning trends
3. Specific actionable recommendations for traffic police
4. Suggested patrol deployment

Keep it concise and professional.
"""

        message = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=500,
            messages=[{"role": "user", "content": prompt}]
        )

        return message.content[0].text

    except Exception as e:
        # Fallback: Generate summary without API
        return generate_fallback_summary(stats)

def generate_fallback_summary(stats):
    """
    Generate summary without API key
    """
    summary = f"""
VIOSENSE AI - WEEKLY TRAFFIC SAFETY REPORT
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
{'='*50}

EXECUTIVE SUMMARY:
VioSense AI detected {stats['total']} traffic violations
during the monitoring period in Bengaluru.

KEY FINDINGS:
- Most common violation: {stats['top_violation']}
  ({stats['top_violation_count']} incidents)
- Highest risk zone: {stats['top_location']}
  ({stats['top_location_count']} violations recorded)
- Critical risk incidents: {stats['critical']}
- Habitual offenders identified: {stats['repeat_offenders']}

RISK ASSESSMENT:
{'CRITICAL - Immediate action required' if stats['critical'] > 5
 else 'MODERATE - Enhanced monitoring recommended'}

RECOMMENDATIONS:
1. Deploy additional officers at {stats['top_location']}
2. Focus enforcement on {stats['top_violation']} violations
3. Issue notices to {stats['repeat_offenders']} repeat offenders
4. Increase patrol during peak hours: 6PM - 8PM

ACTION REQUIRED:
Traffic police should prioritize {stats['top_location']}
with minimum 3 officers during evening peak hours.

--- Generated by VioSense AI Enforcement Platform ---
"""
    return summary

if __name__ == "__main__":
    print("Generating AI Weekly Summary...")
    print("="*50)
    summary = generate_ai_summary()
    print(summary)
    print("="*50)
    print("Summary generated successfully!")